[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Kevin Simpson <ktsimpso@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
anyhow = "1.0.34"
simple-error = "0.2.2"
